server:
  port: 9999
spring:
  application:
    name: ribbon-consumer
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:1111/eureka/
    #定期更新服务列表, 每40秒更新一次服务列表
    registry-fetch-interval-seconds: 10

